### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by bsantosh909** [TheLearneer/job-portal-system#2]
## Database
Currently the database is handled by **typeorm**. The current structure is done as per the requirements, but it is necessary to properly structure the database

### Tasks to do
- [ ] Properly structure database
- [ ] Properly map relations
- [ ] Validate field type and related informations
- [ ] Update the remaining codes as per the changes made here
